INSERT INTO A2(text, les_id) VALUES('He said that the perfomance hadn\'t lived up to his expectations.', 10 );
INSERT INTO A2(text, les_id) VALUES('He said that he had never been to China before.', 10 );
INSERT INTO A2(text, les_id) VALUES('To be honest, I\'ve always wanted to do something useful and meaningfull in my life.', 10 );
INSERT INTO A2(text, les_id) VALUES('I\'ve never seen anything like it before.', 10 );
INSERT INTO A2(text, les_id) VALUES('I told him that I always wanted to go to an English-speaking country.', 10 );
INSERT INTO A2(text, les_id) VALUES('It didn\'t lived up to  my expectations.', 10 );
INSERT INTO A2(text, les_id) VALUES('I didn\'t pay attention to it in the beginning but then I realized the seriousness of this problem.', 10 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t achieved to this aim yet but I\'m going to do it in the near future.', 10 );
INSERT INTO A2(text, les_id) VALUES('When I saw it for the first time I was really shocked.', 10 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t solved this problem yet but I\'m going to do something about it in the near future.', 10 );
INSERT INTO A2(text, les_id) VALUES('She said that she had never experienced such a feeling before.', 10 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t decided it yet.', 10 );
INSERT INTO A2(text, les_id) VALUES('When I saw them, they were arguing about something.', 10 );
INSERT INTO A2(text, les_id) VALUES('When he explained everything to me I realized that I had made a mistake.', 10 );
INSERT INTO A2(text, les_id) VALUES('I remembered that I had left the keys at home.', 10 );
INSERT INTO A2(text, les_id) VALUES('I\'ve always wanted to visit an English-speaking country.', 10 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t reached a strong Intermediate level in English yet but it\'s in my plans.', 10 );
INSERT INTO A2(text, les_id) VALUES('I\'ve just got a message from him.', 10 );
INSERT INTO A2(text, les_id) VALUES('I\'ve never been to China.', 10 );
INSERT INTO A2(text, les_id) VALUES('Time was passing very slovely.', 10 );
INSERT INTO A2(text, les_id) VALUES('We were waiting and waiting.', 10 );
INSERT INTO A2(text, les_id) VALUES('Everything was so uncertain.', 10 );
INSERT INTO A2(text, les_id) VALUES('We all understood that it was the best offer, because we had never seen anything like it before.', 10 );
INSERT INTO A2(text, les_id) VALUES('To tell the truth, I have never had this kind of problems before.', 10 );
INSERT INTO A2(text, les_id) VALUES('I explained it to him.', 10 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t reached an Intermediate level in English yet but I\'m going to it soon.', 10 );
