INSERT INTO A2(text, les_id) VALUES('		Preset Perfect', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to an English-speaking country?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to England?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to the USA.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to this country.', 1 );
INSERT INTO A2(text, les_id) VALUES('Were you in America last year?', 1 );
INSERT INTO A2(text, les_id) VALUES('Were you in China two years ago?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you been to India?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you been to China?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you been abroad?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been abroad?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to Spain? Not yet.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to Italy? I was there last year.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to the USA? I was there two years ago.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to Latin America? I haven\'t been there yet.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to an English-speaking country? Not yet but it\'s in my plans.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to an English-speaking country? I haven\'t been there yet but it\'s in my plans.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve just arrived in England.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve just arrived at the airport.', 1 );
INSERT INTO A2(text, les_id) VALUES('He\'s just arrived at the party.', 1 );
INSERT INTO A2(text, les_id) VALUES('He\'s already mentioned it during his conversation.', 1 );
INSERT INTO A2(text, les_id) VALUES('She\'s already mentioned it during the conversation.', 1 );
INSERT INTO A2(text, les_id) VALUES('As I know, they\'ve already taken proper measures.', 1 );
INSERT INTO A2(text, les_id) VALUES('She\'s always wanted to study psychology.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve always wanted to devote more free time to it.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve always to succeed in life.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve never thought about it.', 1 );
INSERT INTO A2(text, les_id) VALUES('To be honest, I\'ve never considered it really seriously.', 1 );
INSERT INTO A2(text, les_id) VALUES('To be honest, I\'ve never been to an English-speaking country but I\'m going to do it one day.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve been there many times.', 1 );
INSERT INTO A2(text, les_id) VALUES('You know, I\'ve heard it a thousand times.', 1 );
INSERT INTO A2(text, les_id) VALUES('You know, I\'ve heard it so many times.', 1 );
INSERT INTO A2(text, les_id) VALUES('You know, I\'ve been there so many times.', 1 );
INSERT INTO A2(text, les_id) VALUES('As I know, he released this album about a year ago.', 1 );
