INSERT INTO Verb(first, second, third, translate, type) VALUES('sign','signed','signed','sign the documents','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('support','supported','supported','support the initiative','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('forget','forgot','forgotten','I don't remember.','irregular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('agree','agreed','agreed','accept','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('earn','earned','earned','earn money','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('thank','thanked','thanked','thank you','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('stand','stood','stood','stojat','irregular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('enter','entered','entered','enter the room, enter a university','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('damage','damaged','damaged','regular','damaged it badly');
INSERT INTO Verb(first, second, third, translate, type) VALUES('deal','dealt','dealt','deal with people','irregular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('celebrate','celebrated','celebrated','celbrate his birthday','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('want','wanted','wanted','want to do it','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('send','sent','sent','sent a message','irregular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('stop','stoped','stoped','stop doing something','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('doubt','doubted','doubted','doubt that it'll happen','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('sound','sounded','sounded','sound really strange','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('win','won','won','Who is winning now?','irregular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('fall','fell','fallen','He fall','irregular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('pass','passed','passed','pass the exam','regular');
INSERT INTO Verb(first, second, third, translate, type) VALUES('publish','published','published','publish the report','regular');
