CREATE TABLE A2
(
	id Int not Null AUTO_INCREMENT,
	text TINYTEXT,
        les_id Int,
        ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK PRIMARY KEY (id) 	
) default charset utf8;

INSERT INTO A2(text, les_id) VALUES('		Preset Perfect', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to an English-speaking country?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to England?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to the USA.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to this country.', 1 );
INSERT INTO A2(text, les_id) VALUES('Were you in America last year?', 1 );
INSERT INTO A2(text, les_id) VALUES('Were you in China two years ago?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you been to India?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you been to China?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you been abroad?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been abroad?', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to Spain? Not yet.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to Italy? I was there last year.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to the USA? I was there two years ago.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to Latin America? I haven\'t been there yet.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to an English-speaking country? Not yet but it\'s in my plans.', 1 );
INSERT INTO A2(text, les_id) VALUES('Have you ever been to an English-speaking country? I haven\'t been there yet but it\'s in my plans.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve just arrived in England.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve just arrived at the airport.', 1 );
INSERT INTO A2(text, les_id) VALUES('He\'s just arrived at the party.', 1 );
INSERT INTO A2(text, les_id) VALUES('He\'s already mentioned it during his conversation.', 1 );
INSERT INTO A2(text, les_id) VALUES('She\'s already mentioned it during the conversation.', 1 );
INSERT INTO A2(text, les_id) VALUES('As I know, they\'ve already taken proper measures.', 1 );
INSERT INTO A2(text, les_id) VALUES('She\'s always wanted to study psychology.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve always wanted to devote more free time to it.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve always to succeed in life.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve never thought about it.', 1 );
INSERT INTO A2(text, les_id) VALUES('To be honest, I\'ve never considered it really seriously.', 1 );
INSERT INTO A2(text, les_id) VALUES('To be honest, I\'ve never been to an English-speaking country but I\'m going to do it one day.', 1 );
INSERT INTO A2(text, les_id) VALUES('I\'ve been there many times.', 1 );
INSERT INTO A2(text, les_id) VALUES('You know, I\'ve heard it a thousand times.', 1 );
INSERT INTO A2(text, les_id) VALUES('You know, I\'ve heard it so many times.', 1 );
INSERT INTO A2(text, les_id) VALUES('You know, I\'ve been there so many times.', 1 );
INSERT INTO A2(text, les_id) VALUES('As I know, he released this album about a year ago.', 1 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t found any suitable yet.', 2 );
INSERT INTO A2(text, les_id) VALUES('                 Past Continous', 3 );
INSERT INTO A2(text, les_id) VALUES('When she called me, I was having a rest.', 3 );
INSERT INTO A2(text, les_id) VALUES('When he called me, I was stying at home.', 3 );
INSERT INTO A2(text, les_id) VALUES('When I got a call from him, I was walking somewhwere in the park.', 3 );
INSERT INTO A2(text, les_id) VALUES('When I saw them, they were playing at the stadium.', 3 );
INSERT INTO A2(text, les_id) VALUES('When I came home, she was cooking something.', 3 );
INSERT INTO A2(text, les_id) VALUES('She was cooking something very tasty, when I came home.', 3 );
INSERT INTO A2(text, les_id) VALUES('When she called me, I was thinking about her.', 3 );
INSERT INTO A2(text, les_id) VALUES('When I was working, they were having a rest.', 3 );
INSERT INTO A2(text, les_id) VALUES('When I was trying to fall asleep, I heard a very strange noise.', 3 );
INSERT INTO A2(text, les_id) VALUES('When I was trying to fall asleep, the boys were playing very loudly.', 3 );
INSERT INTO A2(text, les_id) VALUES('When I was trying to fall asleep, the men were talking about something very loudly.', 3 );
INSERT INTO A2(text, les_id) VALUES('While we were waiting, we were getting more and more nervous.', 3 );
INSERT INTO A2(text, les_id) VALUES('We were getting more and more nervous while we were waiting for the exam results.', 3 );
INSERT INTO A2(text, les_id) VALUES('While we were waiting for this anouncement we were getting more and more nervous.', 3 );
INSERT INTO A2(text, les_id) VALUES('I was watching this video yesterday at this time.', 3 );
INSERT INTO A2(text, les_id) VALUES('I was reading a very thrilling story yesterday at 3 o\'clock in the afternoon.', 3 );
INSERT INTO A2(text, les_id) VALUES('I was working all day yesterday.', 3 );
INSERT INTO A2(text, les_id) VALUES('I was learning English all day yesterday.', 3 );
INSERT INTO A2(text, les_id) VALUES('I was staying at home all day yesterday.', 3 );
INSERT INTO A2(text, les_id) VALUES('What were you doing there? I was waiting for my friend.', 3 );
INSERT INTO A2(text, les_id) VALUES('The sun was shining very brightly and the birds were singing.', 3 );
INSERT INTO A2(text, les_id) VALUES('When I woke up, the sun was shining very brightly.', 3 );
INSERT INTO A2(text, les_id) VALUES('When I came home, I drank a cup of tea.', 3 );
INSERT INTO A2(text, les_id) VALUES('When I came home, I fell asleep.', 3 );
INSERT INTO A2(text, les_id) VALUES('He fell asleep when he came home.', 3 );
INSERT INTO A2(text, les_id) VALUES('I was waiting for your message.', 3 );
INSERT INTO A2(text, les_id) VALUES('I was waiting for your answer with impatience.', 3 );
INSERT INTO A2(text, les_id) VALUES('To tell the truth, I was waiting for your message with impatience.', 3 );
INSERT INTO A2(text, les_id) VALUES('To tell the truth, I was waiting for this news with impatience.', 3 );
INSERT INTO A2(text, les_id) VALUES('		Past Simple and Past Continous def', 5 );
INSERT INTO A2(text, les_id) VALUES('When I studied at school, I didn\'t pay attention to it.', 5 );
INSERT INTO A2(text, les_id) VALUES('When I studied at university, my friends and I often discussed it.', 5 );
INSERT INTO A2(text, les_id) VALUES('When I was waiting for him, I was revising the lesson.', 5 );
INSERT INTO A2(text, les_id) VALUES('I revised all the lessons.', 5 );
INSERT INTO A2(text, les_id) VALUES('While I was reading that book, I was getting more and more interested in it because the plot was so thrilling.', 5 );
INSERT INTO A2(text, les_id) VALUES('While I was reading that book, I was more and more interested in it, because it was such a thrilling book.', 5 );
INSERT INTO A2(text, les_id) VALUES('I got more interested in this kind of issues.', 5 );
INSERT INTO A2(text, les_id) VALUES('It started raining and we decided to go home.', 5 );
INSERT INTO A2(text, les_id) VALUES('It was raining all day.', 5 );
INSERT INTO A2(text, les_id) VALUES('When I arrived at the station, he was waiting for me.', 5 );
INSERT INTO A2(text, les_id) VALUES('When it happened, I started thinking about it more seriously.', 5 );
INSERT INTO A2(text, les_id) VALUES('When it happened to me, I started thinking about it much more seriously.', 5 );
INSERT INTO A2(text, les_id) VALUES('When I saw him, I asked him that question.', 5 );
INSERT INTO A2(text, les_id) VALUES('When it started raining so heavily, I decided not to go there.', 5 );
INSERT INTO A2(text, les_id) VALUES('When it started snowing so heavily, I decided to cancel that meeting.', 5 );
INSERT INTO A2(text, les_id) VALUES('What were you doing, when you saw it?', 5 );
INSERT INTO A2(text, les_id) VALUES('What were you doing, when such an unpleasant thihg happened?', 5 );
INSERT INTO A2(text, les_id) VALUES('It was a very difficult situation. I was working hard. I was trying to do my best to earn enough money to live on.', 5 );
INSERT INTO A2(text, les_id) VALUES('It was such a difficult situation. I was working so much. I was trying to do my best to earn enough money for a living.', 5 );
INSERT INTO A2(text, les_id) VALUES('The situation was getting out of control and, to be honest, I didn\'t know what to do.', 5 );
INSERT INTO A2(text, les_id) VALUES('While I was reading that book, I was getting more and more interested in it because the plot was so thrilling.', 6 );
INSERT INTO A2(text, les_id) VALUES('What were you doing when you saw it?', 6 );
INSERT INTO A2(text, les_id) VALUES('I got more interested in this kind of issues.', 6 );
INSERT INTO A2(text, les_id) VALUES('When it happened to me I started, thinking about it much more seriously.', 6 );
INSERT INTO A2(text, les_id) VALUES('When I studied at university my friends and I often discussed it.', 6 );
INSERT INTO A2(text, les_id) VALUES('It was a very difficult situation. I was working really hard. I was trying to do my best to earn enough money to live on.', 6 );
INSERT INTO A2(text, les_id) VALUES('When I arrived at the station, he was waiting for me.', 6 );
INSERT INTO A2(text, les_id) VALUES('It started raining and we decided to go home.', 6 );
INSERT INTO A2(text, les_id) VALUES('It was such a difficult situation. I was working so much. I was trying to do my best to earn enough money for a living.', 6 );
INSERT INTO A2(text, les_id) VALUES('When it happened, I started thinking about it more seriously.', 6 );
INSERT INTO A2(text, les_id) VALUES('When it started snowing so heaviely, I decided to cancel that meeting.', 6 );
INSERT INTO A2(text, les_id) VALUES('The situation was getting out of control and, to be honest, I didn\'t know what to do.', 6 );
INSERT INTO A2(text, les_id) VALUES('When I saw him I asked him that question.', 6 );
INSERT INTO A2(text, les_id) VALUES('When I was waiting for him, I was revising the lesson.', 6 );
INSERT INTO A2(text, les_id) VALUES('What were you doing when such an unpleasant thing happened?', 6 );
INSERT INTO A2(text, les_id) VALUES('When it started raining so heavily, I decided not to go there.', 6 );
INSERT INTO A2(text, les_id) VALUES('I revised all the lessons.', 6 );
INSERT INTO A2(text, les_id) VALUES('When I studied at school, I didn\'t pay attention to it. ', 6 );
INSERT INTO A2(text, les_id) VALUES('It was snowing all day.', 6 );
INSERT INTO A2(text, les_id) VALUES('While I was reading that book, I was more and more interested in it because it was such a thrilling story.', 6 );
INSERT INTO A2(text, les_id) VALUES('            Past Perfect', 7 );
INSERT INTO A2(text, les_id) VALUES('had done', 7 );
INSERT INTO A2(text, les_id) VALUES('He said that he had won. He won and then he told me about it.', 7 );
INSERT INTO A2(text, les_id) VALUES('I knew that it had already happened.', 7 );
INSERT INTO A2(text, les_id) VALUES('I was so happy because I had passed the test successfully.', 7 );
INSERT INTO A2(text, les_id) VALUES('When I came home she had already cooked dinner.', 7 );
INSERT INTO A2(text, les_id) VALUES('By the time I finished school I had already reached an Intermediate level in English.', 7 );
INSERT INTO A2(text, les_id) VALUES('I had already left home by the time they arrived.', 7 );
INSERT INTO A2(text, les_id) VALUES('I understood that I had made a mistake.', 7 );
INSERT INTO A2(text, les_id) VALUES('He said that he had failed the test.', 7 );
INSERT INTO A2(text, les_id) VALUES('She told me that no one had noticed it.', 7 );
INSERT INTO A2(text, les_id) VALUES('I knew that they had deceived her.', 7 );
INSERT INTO A2(text, les_id) VALUES('I found out that they had deceived him.', 7 );
INSERT INTO A2(text, les_id) VALUES('I found out that they had told me a lie.', 7 );
INSERT INTO A2(text, les_id) VALUES('I had finished doing it by that time.', 7 );
INSERT INTO A2(text, les_id) VALUES('I had finished doing everything by three o\'clock.', 7 );
INSERT INTO A2(text, les_id) VALUES('When he arrived at the airport, the plane had already taken off.', 7 );
INSERT INTO A2(text, les_id) VALUES('When she arrived at the airport, the plane hadn\'t landed yet.', 7 );
INSERT INTO A2(text, les_id) VALUES('I had finished everything by the time she called me.', 7 );
INSERT INTO A2(text, les_id) VALUES('I had finished watching that video by the time they came to me.', 7 );
INSERT INTO A2(text, les_id) VALUES('She said that he had won but I didn\'t believe her.', 7 );
INSERT INTO A2(text, les_id) VALUES('He said that he had never been there but it looked very strange.', 7 );
INSERT INTO A2(text, les_id) VALUES('I told him that I had improved my English significantly thanks to this method.', 7 );
INSERT INTO A2(text, les_id) VALUES('She said that she had never been to such a beautiful place because it looked like a real paradise.', 7 );
INSERT INTO A2(text, les_id) VALUES('I had finished everything by the time she called me.', 8 );
INSERT INTO A2(text, les_id) VALUES('When he arrived at the airport the plane had already taken off.', 8 );
INSERT INTO A2(text, les_id) VALUES('When I came home, she had already cooked dinner.', 8 );
INSERT INTO A2(text, les_id) VALUES('When she arrived at the airport the plane had not landed yet.', 8 );
INSERT INTO A2(text, les_id) VALUES('I told him that I had improved my English significantly thanks to this method.', 8 );
INSERT INTO A2(text, les_id) VALUES('I knew that it had already happened.', 8 );
INSERT INTO A2(text, les_id) VALUES('I found out that they had told me a lie.', 8 );
INSERT INTO A2(text, les_id) VALUES('I found out that they had deceived him.', 8 );
INSERT INTO A2(text, les_id) VALUES('He said that he had won.', 8 );
INSERT INTO A2(text, les_id) VALUES('She said that he had won but I didn\'t believe her.', 8 );
INSERT INTO A2(text, les_id) VALUES('I knew that they had deceived her.', 8 );
INSERT INTO A2(text, les_id) VALUES('I understood that I had made a mistake.', 8 );
INSERT INTO A2(text, les_id) VALUES('I was so happy because I had passed the test successfully.', 8 );
INSERT INTO A2(text, les_id) VALUES('He said that he had never been there, but it looked very strange.', 8 );
INSERT INTO A2(text, les_id) VALUES('I had finished doing it by that time.', 8 );
INSERT INTO A2(text, les_id) VALUES('I had finished doing everything by threee o\'clock.', 8 );
INSERT INTO A2(text, les_id) VALUES('I had finished watching that movie by the time they came to me.', 8 );
INSERT INTO A2(text, les_id) VALUES('I had already left home by the time they arrived.', 8 );
INSERT INTO A2(text, les_id) VALUES('She told me that no one had noticed it.', 8 );
INSERT INTO A2(text, les_id) VALUES('He said that he had failed the test.', 8 );
INSERT INTO A2(text, les_id) VALUES('By the time I finished school I had already reached an Intermediate level in English.', 8 );
INSERT INTO A2(text, les_id) VALUES('She said that she had never been to such a beautiful place because it looked like a real paradise.', 8 );
INSERT INTO A2(text, les_id) VALUES('I\'ve always wanted to visit an English-speaking country.', 9 );
INSERT INTO A2(text, les_id) VALUES('I told him that I had always wanted to go to an English-speaking country.', 9 );
INSERT INTO A2(text, les_id) VALUES('When I saw them they were arguing about something.', 9 );
INSERT INTO A2(text, les_id) VALUES('I explained it to him.', 9 );
INSERT INTO A2(text, les_id) VALUES('When he explained to me everything, I realised that I had made a mistake.  ', 9 );
INSERT INTO A2(text, les_id) VALUES('I\'ve never been to China.', 9 );
INSERT INTO A2(text, les_id) VALUES('He said that he had never been to China before.', 9 );
INSERT INTO A2(text, les_id) VALUES('Time was passing very slovely.', 9 );
INSERT INTO A2(text, les_id) VALUES('We were waiting and waiting.', 9 );
INSERT INTO A2(text, les_id) VALUES('Everything was very uncertain.', 9 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t reached a strong Intermediate level in English yet but it\'s in my plans.', 9 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t reached an Intermediate level in English yet but I\'m going to do it soon.', 9 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t achieved this aim yet but I\'m going to do it in the near future.', 9 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t solve to this problem yet, but I\'m going to do something about it in the near future. ', 9 );
INSERT INTO A2(text, les_id) VALUES('It didn\'t live up to my expectations.', 9 );
INSERT INTO A2(text, les_id) VALUES('He said that the performance hadn\'t lived up his expectations.', 9 );
INSERT INTO A2(text, les_id) VALUES('I\'ve just got a message from him.', 9 );
INSERT INTO A2(text, les_id) VALUES('I remembered that I had left the keys at home.', 9 );
INSERT INTO A2(text, les_id) VALUES('I\'ve never seen anything like it before.', 9 );
INSERT INTO A2(text, les_id) VALUES('We all understood that it was the best offer because we had never seen anything like it before.', 9 );
INSERT INTO A2(text, les_id) VALUES('When I saw it for the first time I was really shocked.', 9 );
INSERT INTO A2(text, les_id) VALUES('I didn\'t pay attention to it in the beggining, but then I understood the seriousness of this problem.', 9 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t decided it yet.', 9 );
INSERT INTO A2(text, les_id) VALUES('She said that she had never experienced such a felling before.', 9 );
INSERT INTO A2(text, les_id) VALUES('To tell the truth, I\'ve never had this kind of problems.', 9 );
INSERT INTO A2(text, les_id) VALUES('To be honest, I\'ve always wanted to do something useful and meaningful in my life.', 9 );
INSERT INTO A2(text, les_id) VALUES('He said that the perfomance hadn\'t lived up to his expectations.', 10 );
INSERT INTO A2(text, les_id) VALUES('He said that he had never been to China before.', 10 );
INSERT INTO A2(text, les_id) VALUES('To be honest, I\'ve always wanted to do something useful and meaningfull in my life.', 10 );
INSERT INTO A2(text, les_id) VALUES('I\'ve never seen anything like it before.', 10 );
INSERT INTO A2(text, les_id) VALUES('I told him that I always wanted to go to an English-speaking country.', 10 );
INSERT INTO A2(text, les_id) VALUES('It didn\'t lived up to  my expectations.', 10 );
INSERT INTO A2(text, les_id) VALUES('I didn\'t pay attention to it in the beginning but then I realized the seriousness of this problem.', 10 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t achieved to this aim yet but I\'m going to do it in the near future.', 10 );
INSERT INTO A2(text, les_id) VALUES('When I saw it for the first time I was really shocked.', 10 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t solved this problem yet but I\'m going to do something about it in the near future.', 10 );
INSERT INTO A2(text, les_id) VALUES('She said that she had never experienced such a feeling before.', 10 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t decided it yet.', 10 );
INSERT INTO A2(text, les_id) VALUES('When I saw them, they were arguing about something.', 10 );
INSERT INTO A2(text, les_id) VALUES('When he explained everything to me I realized that I had made a mistake.', 10 );
INSERT INTO A2(text, les_id) VALUES('I remembered that I had left the keys at home.', 10 );
INSERT INTO A2(text, les_id) VALUES('I\'ve always wanted to visit an English-speaking country.', 10 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t reached a strong Intermediate level in English yet but it\'s in my plans.', 10 );
INSERT INTO A2(text, les_id) VALUES('I\'ve just got a message from him.', 10 );
INSERT INTO A2(text, les_id) VALUES('I\'ve never been to China.', 10 );
INSERT INTO A2(text, les_id) VALUES('Time was passing very slovely.', 10 );
INSERT INTO A2(text, les_id) VALUES('We were waiting and waiting.', 10 );
INSERT INTO A2(text, les_id) VALUES('Everything was so uncertain.', 10 );
INSERT INTO A2(text, les_id) VALUES('We all understood that it was the best offer, because we had never seen anything like it before.', 10 );
INSERT INTO A2(text, les_id) VALUES('To tell the truth, I have never had this kind of problems before.', 10 );
INSERT INTO A2(text, les_id) VALUES('I explained it to him.', 10 );
INSERT INTO A2(text, les_id) VALUES('I haven\'t reached an Intermediate level in English yet but I\'m going to it soon.', 10 );
